### ISSUE TITLE
What are the credentials required to access the SDK?

### ISSUE THREAD

**Issue by mtwalli** [Insta360Develop/CameraSDK-Android#14]
- Android SDK docs says `see SDK demo` ,but there is no demo. Cloud you please help ?

**Comment by mtwalli** [comment]
@EternalSoySauce FYI

**Comment by EternalSoySauce** [comment]
Apply for the access to use sdk by this link. After passing, you can contact the industry manager to ask for sdk demo.

https://www.insta360.com/mobile/sdk/home

**Comment by ilker-aktuna** [comment]
Hi,

I applied for the access to SDK. They sent me an email with links to this repository.
But there is no credential in the email.
How do I get the credentials ?

thanks

**Comment by EternalSoySauce** [comment]
For questions about sdk registration, please communicate with our technical support.

This is the email address：
support@insta360.com

**Comment by ilker-aktuna** [comment]
ok. I am contacting them. But I really don't understand why we have authorization requirement to Android SDK and not IOS SDK.
that's weird.
