### ISSUE TITLE
Error during preview

### ISSUE THREAD

**Issue by fareed945** [Insta360Develop/CameraSDK-Android#16]
Hey,
I face the following error while previewing using the insta 360 onex2

java.lang.NullPointerException: Attempt to invoke interface method 'void com.arashivision.onestream.pipeline.ICameraPreviewPipeline.onGyroStream(byte[], long)' on a null object reference\n\tat com.arashivision.camera.stream.StreamProcess.processGyro(StreamProcess.java:595)\n\tat com.arashivision.camera.stream.StreamProcess.precoss(StreamProcess.java:255)\n\tat com.arashivision.camera.stream.StreamProcess.access$100(StreamProcess.java:42)\n\tat com.arashivision.camera.stream.StreamProcess$4.run(StreamProcess.java:230)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\n"

What might be the issue ?

FYI: @EternalSoySauce

**Comment by EternalSoySauce** [comment]
If it appears every time, check if you have performed the following operations.
![image](https://user-images.githubusercontent.com/31469540/141958004-d124d008-ad3a-49ea-a508-3233645a7365.png)

If it happened by accident, update the sdk to v1.3.14. It has been fixed in this version.

**Comment by fareed945** [comment]
It occurs intermittently, not always.
Sure, will update the SDK accordingly
