### ISSUE TITLE
App crash on export of 72MP resolution images from the Insta360 X3

### ISSUE THREAD

**Issue by cobear25** [Insta360Develop/CameraSDK-Android#32]
The demo app as well as our app currently crashes when we run `ExportUtils.exportImage()` with a high resolution photo from the X3. It works fine for other images, including HDR.

**Comment by mordekai91** [comment]
Hi cobear25, have you solved this?

**Comment by cobear25** [comment]
@mordekai91 We ended up just removing support for older versions of Android. We reached out to Insta360 support and they didn't have any plans to resolve it because they couldn't reproduce it. Basically it's a memory or storage issue that occurs on older devices.
