### ISSUE TITLE
 InstaCameraManager.getInstance().openCamera(InstaCameraManager.CONNECT_TYPE_WIFI);

### ISSUE THREAD

**Issue by houw** [Insta360Develop/CameraSDK-Android#59]
When I call this API, I get the following errors? Do I missing some configs or permissions settings?
<img width="713" alt="Screenshot 2023-10-18 at 02 22 22" src="https://github.com/Insta360Develop/CameraSDK-Android/assets/1150026/2728b97f-d6a8-449e-8d90-458cfd4a5f5f">

Ryan

**Comment by houw** [comment]
I have found the reason. It is because of application name, it should be replace settings

**Comment by mordekai91** [comment]
Hi @houw how do you solve this? Thank you
