### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by Flutter05** [Insta360Develop/CameraSDK-Android#68]
dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.arashivision.sdk:sdkcamera:1.5.3'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'http://nexus.arashivision.com:9999/repository/maven-public/'
            allowInsecureProtocol true
            credentials {
                username = 'Vikas@flyweis.technology'
                password = 'Insta2128!'
            }
        }
    }
}

Getting
Failed to resolve: com.arashivision.sdk:sdkcamera:1.5.3
Show in Project Structure dialog
Show Details
Affected Modules: app

**Comment by abda1014** [comment]
How did u solve this problem ?

**Comment by Flutter05** [comment]
> How did u solve this problem ? I also get the same response

        maven {
            isAllowInsecureProtocol = true
            url = uri("http://nexus.arashivision.com:9999/repository/maven-public/")
            credentials {
                // see sdk demo
                username = "deployment"
                password = "test123"
            }
        }

com.arashivision.sdk:sdkcamera:1.6.4


Use These
