### ISSUE TITLE
Preview pano auto-rotates by itself

### ISSUE THREAD

**Issue by gshcherb** [Insta360Develop/CameraSDK-Android#8]
Preview played in `InstaCapturePlayerView` auto-rotates shifting the current view. This is easily reproducible in SDK Demo app.

SDK v1.3.10.

**Comment by EternalSoySauce** [comment]
I don't really understand what the problem is, can you post a sample picture or gif?

**Comment by EternalSoySauce** [comment]
And the camera can only establish a connection with one app at the same time, make sure that the camera is in an idle state before connecting again

**Comment by gshcherb** [comment]
Please take a look at the video recorded on Samsung S20+. 

https://drive.google.com/file/d/1GgtnlWv4dmpsXiwgsM29YxIIL5l-su-H/view?usp=sharing

I connected phone to camera and started preview. When I open preview first time it shifts a bit, but then stays in fixed position. When I open preview second time and following times it auto-rotates buy itself as is on the video, even though I am not touching neither camera no phone at this moment. This happens in the demo app as well.

Please let me know if you need more info.

**Comment by EternalSoySauce** [comment]
This is an abnormality in the zero drift of the camera gyroscope. There is a gyro calibration function in the camera settings. If the abnormality still occurs after calibrate, you can report to insta customer service or industry manager to help you change the camera.

**Comment by gshcherb** [comment]
Sounds good. Thanks for clarifying.
